import random
import time
while 1==1:
    time.sleep(5)
    randomSeed = random.random()
    randomSeed2 = random.random()
    randomSeed3 = random.random()
    randomSeed4 = random.random()
    randomSeed5 = random.random()
    randomSeed6 = random.random()
    randomSeed7= random.random()
    randomSeed8 = random.random()
    randomSeed9 = random.random()
    randomSeed10 = random.random()
    print("seeds:----------------" "\n" +str(randomSeed), "-"+str(randomSeed))
    print(str(randomSeed2),  "-"+str(randomSeed2))
    print(str(randomSeed3),  "-"+str(randomSeed3))
    print(str(randomSeed4),  "-"+str(randomSeed4))
    print(str(randomSeed5),  "-"+str(randomSeed5))
    print(str(randomSeed6),  "-"+str(randomSeed6))
    print(str(randomSeed7),  "-"+str(randomSeed7))
    print(str(randomSeed8),  "-"+str(randomSeed8))
    print(str(randomSeed9),  "-"+str(randomSeed9))
    print(str(randomSeed10),  "-"+str(randomSeed10))